CREATE TABLE IF NOT EXISTS `DUMMY` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `ITEM_ID`     INT       NOT NULL,
  `PRICE` FLOAT NOT NULL DEFAULT 0.00,
  `LAST_UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
)
;

CREATE TABLE IF NOT EXISTS `REMOTE_DUMMY` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `ITEM_ID`     INT       NOT NULL,
  `PRICE` FLOAT NOT NULL DEFAULT 0.00,
  `LAST_UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
)
;

INSERT INTO DUMMY (ITEM_ID, PRICE, LAST_UPDATED)
 VALUES (1, 1.00, CURRENT_TIMESTAMP() ),
        (2, 3.25, CURRENT_TIMESTAMP() ),
        (3, 7.81, CURRENT_TIMESTAMP() )
;

